osx_image: xcode8
language: objective-c
script:
- set -o pipefail && xcodebuild test -project ViSearchSDK\ViSearchSDK.xcodeproj -scheme ViSearchSDK -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty